export const TRANSLATE_LIST = {
    ru: {
      shop: 'Mагазин',
      home: 'Главная',
      inBasket: 'В корзине',
      goTo: 'Перейти',
      oneProduct: 'товар',
      fewProduct: 'товара',
      manyProduct: 'товаров',
      emptyBasket: 'пусто',
      add: 'Добавить',
      total: 'Итого',
      basket: 'Корзина',
      close: 'Закрыть',
      productName: 'Название товара',
      country: 'Страна производитель',
      category: 'Категория',
      manufactured: 'Год выпуска',
      price: 'Цена',
      pc: 'шт',
      delete: 'Удалить',
    },
    en: {
      shop: 'Shop',
      home: 'Home',
      inBasket: 'In basket',
      goTo: 'Go',
      oneProduct: 'product',
      fewProduct: 'products',
      manyProduct: 'products',
      emptyBasket: 'empty',
      add: 'Add',
      total: 'Total',
      basket: 'Basket',
      close: 'Close',
      productName: 'Product name',
      country: 'Manufacturer country',
      category: 'Category',
      manufactured: 'Year of issue',
      price: 'Price',
      pc: 'pc',
      delete: 'Delete',
    }
  }