# Комментрии к товару

GET http://example.front.ylab.io/api/v1/comments?fields=items(_id,text,dateCreate,author(profile(name)),parent(_id,_type),isDeleted),count&limit=*&search[parent]=65f8322cf3360f03347a6be8

# Остальные методы в http://example.front.ylab.io/api/v1/docs/ (http://localhost:8010/api/v1/docs/)

###
# Создание первого коммента
POST http://example.front.ylab.io/api/v1/comments
Content-Type: application/json
X-Token:ec55d77cdc129c4dffc5dcd61f56a209152a3ee2c226690ed9c73e99727fabc8

{
  "text": "1111",
  "parent": {"_id":  "65f8322cf3360f03347a6bdf", "_type":  "article"}
}


###
# Создание ответа на коммент коммента
POST http://example.front.ylab.io/api/v1/comments
Content-Type: application/json
X-Token: 9311be362c8e3b834e4643935e0e99f4ee6a69afee1fc633c5bcf49a67d6dc82

{
  "text": "net",
  "parent": {"_id":  "65ff256879c52242c46736df", "_type":  "comment"}
}
