# Комментрии к товару

GET http://query.rest/api/v1/comments?fields=items(_id,text,dateCreate,author(profile(name)),parent(_id,_type),isDeleted),count&limit=*&search[parent]=670260bb7dd498df5525e5ed

# Остальные методы в http://query.rest/api/v1/docs/ (http://localhost:8010/api/v1/docs/)

###
# Создание первого коммента
POST http://query.rest/api/v1/comments
Content-Type: application/json
X-Token: 7ee15209d8429544dea8123fbdae254f5f79e6da5d720fec3127d9385b6eb9bc

{
  "text": "Первый коммент!",
  "parent": {"_id":  "670260bb7dd498df5525e5ed", "_type":  "article"}
}


###
# Создание ответа на коммент коммента
POST http://query.rest/api/v1/comments
Content-Type: application/json
X-Token: 40717d1c056933a15c15a0d8ccd6684cd8ff2805b845d9810a4446c85d2f93c4

{
  "text": "Первый ответ на коммент!",
  "parent": {"_id": "68056df17e843dad89610a98", "_type": "comment"}
}
