# Комментрии к товару

GET http://example.front.ylab.io/api/v1/comments?fields=items(_id,text,dateCreate,author(profile(name)),parent(_id,_type),isDeleted),count&limit=*&search[parent]=65f8322cf3360f03347a6be8

# Остальные методы в http://example.front.ylab.io/api/v1/docs/ (http://localhost:8010/api/v1/docs/)

###
# Создание первого коммента
POST http://example.front.ylab.io/api/v1/comments?fields=_id,text,dateCreate,author(profile(name)),parent(_id,_type),isDeleted
Content-Type: application/json
X-Token: 8e6166162f067ba52e4321d4e385bb2325a68eea19feb865a21b1a447313f72f

{
  "text": "Первый коммент!",
  "parent": {"_id":  "65f8322cf3360f03347a6be8", "_type":  "article"}
}


###
# Создание ответа на коммент коммента
POST http://example.front.ylab.io/api/v1/comments
Content-Type: application/json
X-Token: 8e6166162f067ba52e4321d4e385bb2325a68eea19feb865a21b1a447313f72f

{
  "text": "Первый коммент!",
  "parent": {"_id":  "65fc807d48a54759d5ca8cdc", "_type":  "comment"}
}
