###
# Авторизация

POST http://query.rest/api/v1/users/sign
Content-Type: application/json

{
  "login": "test_1",
  "password": "123456"
}

###
# Выход - отмена авториазции для удаления токена

DELETE http://query.rest/api/v1/users/sign
X-Token: b1178ab283942790c7aa39b51232ce3d0db21de35bcc4b48581bcc8c96e61a42
Content-Type: application/json

###
# Свой профиль

GET http://query.rest/api/v1/users/self?fields=*
X-Token: 8da4eaa24950a3ce3d385e5c558924aeae7bedbecedc5c26b8ad3dea67664330
Content-Type: application/json
