###
# Авторизация

POST http://example.front.ylab.io/api/v1/users/sign
Content-Type: application/json

{
  "login": "test_1",
  "password": "123456"
}

###
# Выход - отмена авториазции для удаления токена

DELETE http://example.front.ylab.io/api/v1/users/sign
X-Token: 0ec009b6553485c7684baa0eb9938fd01ccb3ab5c796c93f01b5f98aa3144ffe
Content-Type: application/json

###
# Свой профиль

GET http://example.front.ylab.io/api/v1/users/self
X-Token: d7fef69061bd7fc299da81ce4ae28eba3533c17a72ce4719721236d8d7e403df
Content-Type: application/json
