export const langKeyWords = {
    ru: {
        headTitle: 'Магазин',
        basket: 'Корзина',
        oneItem: 'товар',
        fewItems: 'товара',
        manyItems: 'товаров',
        cartEmpty: 'Пусто',
        amount: 'шт',
        total: 'Итого',
        homepage: 'Главная',
        madeIn: 'Страна производитель',
        category: 'Категория',
        edition: 'Год выпуска',
        price: 'Цена',
        btnAdd: 'Добавить',
        btnDelete: 'Удалить',
    },
    en: {
        headTitle: 'Store',
        basket: 'Basket',
        oneItem: 'item',
        fewItems: 'items',
        manyItems: 'items',
        cartEmpty: 'Empty',
        amount: 'pcs',
        total: 'Total',
        homepage: 'Home',
        madeIn: 'Made in',
        category: 'Category',
        edition: 'Edition',
        price: 'Price',
        btnAdd: 'Add',
        btnDelete: 'Delete',
    },
}