const translations = {
  ru: {
    home: 'Главная',
    shop: 'Магазин',
    catalog: 'Каталог',
    add: 'Добавить',
    manufacturer: 'Страна производитель',
    category: 'Категория',
    year: 'Год выпуска',
    price: 'Цена',
    loading: 'Загрузка...',
    empty: 'пусто',
    item_one: 'товар',
    item_few: 'товара',
    item_many: 'товаров',
    basket: 'Корзина',
    total: 'Итого',
    remove: 'Удалить',
    pcs: 'шт',
  },
  en: {
    home: 'Home',
    shop: 'Shop',
    catalog: 'Catalog',
    add: 'Add',
    manufacturer: 'Manufacturer',
    category: 'Category',
    year: 'Year',
    price: 'Price',
    loading: 'Loading...',
    empty: 'empty',
    item_one: 'item',
    item_few: 'items',
    item_many: 'items',
    basket: 'Basket',
    total: 'Total',
    remove: 'Remove',
    pcs: 'pcs',
  },
};

export default translations;
