const i18Obj = {
  en: {
    store: 'Store',
    basket: 'Basket',
    home: 'Home',
    add: 'Add',
    remove: 'Remove',
    goTo: 'Go to',
    close: 'Close',
    inTheBasket: 'In the basket',
    empty: 'nothing',
    pcs: 'pcs',
    total: 'Total',
    country: 'Сountry of origin',
    category: 'Category',
    edition: 'Edition',
    price: 'Price',
    oneItem: 'item',
    fewItems: 'items',
    manyItems: 'items',
  },
  ru: {
    store: 'Магазин',
    basket: 'Корзина',
    home: 'Главная',
    add: 'Добавить',
    remove: 'Удалить',
    goTo: 'Перейти',
    close: 'Закрыть',
    inTheBasket: 'В корзине',
    empty: 'пусто',
    pcs: 'шт',
    total: 'Итого',
    country: 'Страна производитель',
    category: 'Категория',
    edition: 'Год выпуска',
    price: 'Цена',
    oneItem: 'товар',
    fewItems: 'товара',
    manyItems: 'товаров',
  },
};

export default i18Obj;
