const texts = {
  ru: {
    toggler: 'EN (English)',
    basket: 'Корзина',
    shop: 'Магазин',
    main: 'Главная',
    inBasket: 'В корзине',
    productOne: 'товар',
    productFew: 'товара',
    productMany: 'товаров',
    empty: 'пусто',
    follow: 'Перейти',
    total: 'Итого',
    add: 'Добавить',
    remove: 'Удалить',
    country: 'Страна производитель',
    category: 'Категория',
    edition: 'Год выпуска',
    price: 'Цена',
    close: 'Закрыть',
  },
  en: {
    toggler: 'RU (Русский)',
    basket: 'Basket',
    shop: 'Shop',
    main: 'Main',
    inBasket: 'In basket',
    productOne: 'product',
    productFew: 'products',
    productMany: 'products',
    empty: 'empty',
    follow: 'Follow',
    total: 'Total',
    add: 'Add',
    remove: 'Remove',
    country: 'Producing country',
    category: 'Category',
    edition: 'Year',
    price: 'Price',
    close: 'Close',
  },
};

export default texts;