export const ru = {
    store: 'Магазин',
    basket: 'Корзина',
    mainPage: 'Главная',
    going: 'Перейти',
    empty: 'пусто',
    inBasket: 'В корзине',
    add: 'Добавить',
    close: 'Закрыть',
    delete: 'Удалить',
    country: 'Страна производитель',
    category: 'Категория',
    yearIssue: 'Год выпуска',
    price: 'Цена',
    total: 'Итого',
    pcs: 'Шт',
    oneGood: 'товар',
    fewGood: 'товара',
    manyGood: 'товаров',
    switchLanguage: 'eng'
};

export const eng = {
    store: 'Store',
    basket: 'Basket',
    mainPage: 'Main',
    going: 'Go',
    empty: 'Empty',
    inBasket: 'In the basket',
    add: 'Add',
    close: 'Close',
    delete: 'Delete',
    country: 'Manufacturer country',
    category: 'Category',
    yearIssue: 'Year of issue',
    price: 'Price',
    total: 'Total',
    pcs: 'Pcs',
    oneGood: 'product',
    fewGood: 'goods',
    manyGood: 'products',
    switchLanguage: 'ru'
};